export const state = () => ({
    exercice:50,
    listeTerrains : [
        {'name': 'terrain11', 'color': '', 'image': 'terrain11.png'},	
        {'name': 'terrain10', 'color': '', 'image': 'terrain10.png'},    
        {'name': 'terrain17', 'color': '', 'image': 'terrain17.png'},
        {'name': 'terrain18', 'color': '', 'image': 'terrain18.png'},
        {'name': 'terrain19', 'color': '', 'image': 'terrain19.png'},
        {'name': 'terrain1', 'color': '', 'image': 'terrain1.png'},
        {'name': 'terrain14', 'color': '', 'image': 'terrain14.png'},
        {'name': 'terrain16', 'color': '', 'image': 'terrain16.png'},
        {'name': 'terrain13', 'color': '', 'image': 'terrain13.png'},
    ],
    listeJoueurs : [
        {'name': 'player-mouvement-red', 'image': 'player-mouvement-red.png'},
        {'name': 'player-mouvement-red', 'image': 'player-mouvement-blue.png'},
        {'name': 'player-mouvement-red', 'image': 'player-mouvement-yellow.png'},
        {'name': 'player-mouvement-red', 'image': 'player-mouvement-black.png'},
    ],
    listeGardiens : [
        {'name': 'player-gardien-green', 'image': 'player-gardien-green.png'},
        {'name': 'player-gardien-orange', 'image': 'player-gardien-orange.png'},
        {'name': 'player-gardien-mauve', 'image': 'player-gardien-mauve.png'},
    ],
    listeOutils : [
        {'name': 'ballon', 'image': 'ballon.png'}, 
        {'name': 'source_ballon', 'image': 'source_ballon.png'},
        {'name': 'but', 'image': 'but.png'},    	
        {'name': 'but3', 'image': 'but3.png'},
        {'name': 'but2', 'image': 'but2.png'},
        {'name': 'cone', 'image': 'cone.png'},
        {'name': 'cone-red', 'image': 'cone-red.png'},
        {'name': 'cone-blue-claro', 'image': 'cone-blue-claro.png'},
        {'name': 'cone-yellow', 'image': 'cone-yellow.png'},
        {'name': 'cone2', 'image': 'cone2.png'},
        {'name': 'cone2-red', 'image': 'cone2-red.png'},
        {'name': 'cone2-blue-claro', 'image': 'cone2-blue-claro.png'},
        {'name': 'cone2-yellow', 'image': 'cone2-yellow.png'},
        {'name': 'stair', 'image': 'stair.png'},
        {'name': 'stair-left', 'image': 'stair-left.png'},
        {'name': 'hoop', 'image': 'hoop.png'},
        {'name': 'hoop-red', 'image': 'hoop-red.png'},
        {'name': 'hoop-blue-claro', 'image': 'hoop-blue-claro.png'},
        {'name': 'hoop-yellow', 'image': 'hoop-yellow.png'},
        {'name': 'flag-black', 'image': 'flag-black.png'},
        {'name': 'flag-red', 'image': 'flag-red.png'},
        {'name': 'hurdles-black', 'image': 'hurdles-black.png'},
        {'name': 'hurdles-red', 'image': 'hurdles-red.png'},
        {'name': 'blocking', 'image': 'blocking.png'},
        {'name': 'blocking-red', 'image': 'blocking-red.png'},
        {'name': 'pick', 'image': 'pick.png'},   
        {'name': 'pic-red', 'image': 'pick-red.png'},
    ],
    listeLignes : [
        {'name': 'arrow6', 'image': 'arrow6.png', 'forme': ''},
        {'name': 'arrow15', 'image': 'arrow15.png', 'forme': ''},
        {'name': 'arrow29', 'image': 'arrow29.png', 'forme': ''},
        {'name': 'arrow9', 'image': 'arrow9.png', 'forme': ''},
        {'name': 'arrow31', 'image': 'arrow31.png', 'forme': ''},
        {'name': 'arrow11', 'image': 'arrow11.png', 'forme': ''},
        {'name': 'arrow32', 'image': 'arrow32.png', 'forme': ''},
        {'name': 'arrow28', 'image': 'arrow28.png', 'forme': ''},
        {'name': 'arrow30', 'image': 'arrow30.png', 'forme': ''},
        {'name': 'arrow17', 'image': 'arrow17.png', 'forme': ''},
        {'name': 'arrow20', 'image': 'arrow20.png', 'forme': ''},
        {'name': 'arrow25', 'image': 'arrow25.png', 'forme': ''},
        {'name': 'arrow24', 'image': 'arrow24.png', 'forme': ''},
        {'name': 'arrow26', 'image': 'arrow26.png', 'forme': ''},
        {'name': 'arrow27', 'image': 'arrow27.png', 'forme': ''},
        {'name': 'line1', 'image': 'line1.png', 'forme': ''},
        {'name': 'line1-left', 'image': 'line1-left.png', 'forme': ''},
        {'name': 'line2', 'image': 'line2.png', 'forme': ''},
        {'name': 'line2-left', 'image': 'line2-left.png', 'forme': ''},
    ],
})